#!/bin/bash
#
# Edit by vastxiao
# Date at 20170506 

cd $(dirname $0)
MAINPATH=$(pwd)
cd bloginit || exit 1
hexo version || exit 1
hexo clean
hexo gen
hexo deploy || exit 1
cd ${MAINPATH}
git add . -A
git commit -a -m "update bloginit at $(date +'%F %T')"
git push

